### ISSUE TITLE
What does the loom format dataset look like specifically? 

### ISSUE THREAD

**Issue by xuebaliang** [scvae/scvae#7]
hello. recently I read your paper and it is a good work. I want to use your framework to obtain the candidate cluster of my dataset, but it seems to be not easy since I do not know the specific data form that I should input. Usually, we just need to input the count data(cell by gene) and labels(if have). But in your code, it seems to do some prepared work about data. Thus can you give me some advice specific if I want to use your framework? Or directly use your github code instead the scvae package? I am confused about the input data format. Thanks!

**Comment by xuebaliang** [comment]
And is the main matrix of your loom format file gene by cell?(row represent genes, column represent cells)?

**Comment by chgroenbech** [comment]
In the next release, scVAE follows [Loompy’s conventions](http://linnarssonlab.org/loompy/format/index.html) more precisely.

For now, scVAE deviates from the conventions by using `Cell` instead of `CellID`, and it only supports `ClusterID` for labels.

You should also be able to use specify count data and labels in a JSON file as described in the README.
